language: python

sudo: false

python:
  - 3.5

env:
  - export FAIL_ON_EXTERNAL_DEPRECATION='False'
  - export FAIL_ON_EXTERNAL_DEPRECATION='True'

matrix:
  allow_failures:
    - env: export FAIL_ON_EXTERNAL_DEPRECATION='True'


install:
  - DEPS="nose numpy scipy matplotlib ipython h5py sympy scikit-learn dill natsort mock setuptools"
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $DEPS
  - conda install pip
  - pip install coverage coveralls request
  - python setup.py install

before_install:
  # Does not matter which miniconda we get, we still create a virtualenv
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  # miniconda is not always up-to-date with conda.
  - conda update --yes conda
script: python continuous_integration/nosetest.py --with-coverage hyperspy
after_success:
    coveralls
