language: python

sudo: false

python:
  - 3.5

env:
  - export FAIL_ON_EXTERNAL_DEPRECATION='False'
  - export FAIL_ON_EXTERNAL_DEPRECATION='True'

matrix:
  allow_failures:
    - env: export FAIL_ON_EXTERNAL_DEPRECATION='True'

before_install:
  # Does not matter which miniconda we get, we still create a virtualenv
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  # miniconda is not always up-to-date with conda.
  - conda update --yes conda

install:
  - DEPS="nose numpy scipy matplotlib ipython h5py sympy scikit-learn dill natsort mock setuptools"
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION $DEPS
  - source activate testenv
  - conda install pip
  - pip install coverage coveralls traits traitsui request
  - python setup.py install

script: python continuous_integration/nosetest.py --with-coverage hyperspy
after_success:
    coveralls
